name: Force Sync to GitLab (no history)

on:
  push:
    branches:
      - master

jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 仍推荐完整 checkout，防止未来遇到奇怪的问题

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add GitLab remote
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/klcb2010/box.git

      - name: Force push to GitLab (overwrite history)
        run: |
          git push --force gitlab master
